spring.application.name=spring-data-rest
server.port=8082

spring.datasource.url=jdbc:postgresql://containers-us-west-12.railway.app:5432/railway
spring.datasource.username=postgres
spring.datasource.password=MKsyfbarZbaWoaZMpFZxjoqmiCRzVrjR
#spring.jpa.hibernate.ddl-auto=update


#spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
#spring.datasource.username=postgres
#spring.datasource.password=MKsyfbarZbaWoaZMpFZxjoqmiCRzVrjR
#spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.http.encoding.enabled=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
razorpay.key=rzp_test_RnzkgRY4XHy0Xi
razorpay.secret=gkxxGaFblj3FK0KYPHhocXsW
